version: "3"
services:
  consumer-app:
    build:
      context: ./php
      args:
        DEBUG_HOST: ${DEBUG_HOST}
        DEBUG_PORT: ${DEBUG_PORT}
    container_name: consumer-app
    restart: unless-stopped
    env_file:
      - ../../.env.local.example
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/
    volumes:
      - ../../:/var/www/

  consumer-web:
    image: nginx:latest
    container_name: consumer-web
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./php/site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Europe/Berlin

  consumer-mysql:
    image: mysql
    container_name: consumer-db
    restart: unless-stopped
    tty: true
    volumes:
      - data-mysql:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

volumes:
  data-mysql:
    driver: local
